# This is a basic workflow to help you get started with Actions

name: Deploy Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - staging

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - uses: actions/checkout@master
      - name: Install dependancies
        run: yarn install
      - name: Deploy lambdas
        working-directory: lambdas
        run: |
          yarn sls config credentials --provider aws --profile covid --secret "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --key "${{ secrets.AWS_ACCESS_KEY_ID }}"
          yarn sls deploy --verbose --stage staging
        env:
          AWS_ACCESS_KEY_ID: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          AWS_SECRET_ACCESS_KEY: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          GOOGLE_API_KEY: '${{ secrets.GOOGLE_API_KEY }}'
          SPREADSHEET_ID: '${{ secrets.SPREADSHEET_ID }}'
          SHEET_ID: '${{ secrets.SHEET_ID }}'
          GOOGLE_PRIVATE_KEY: '${{ secrets.GOOGLE_PRIVATE_KEY }}'
          GOOGLE_CLIENT_EMAIL: '${{ secrets.GOOGLE_CLIENT_EMAIL }}'
          PUSHER_KEY: '${{ secrets.PUSHER_KEY }}'
          PUSHER_SECRET: '${{ secrets.PUSHER_SECRET }}'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      - name: 'Update client endpoint'
        run: 'node scripts/netlify-snippets.js'
        env:
          NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STAG_ID }}
      # - name: Run tests
      #   run: yarn test:e2e
